/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/MusicBox.gltf')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    console.log("A: ", actions);
    actions["Take 001"].play();
  });
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-7.29, 23, -5.08]}>
            <group position={[-0.12, 1.58, -0.14]}>
              <mesh geometry={nodes.pCylinder51_Setelite_0.geometry} material={nodes.pCylinder51_Setelite_0.material} />
            </group>
            <group position={[7.29, -22.8, 5.08]}>
              <mesh
                geometry={nodes.polySurface9_Setelite_0.geometry}
                material={nodes.polySurface9_Setelite_0.material}
              />
            </group>
            <group position={[1.1, 4.68, 1.03]}>
              <group position={[0.47, -3.38, 3.28]}>
                <mesh geometry={nodes.pSphere12_Setelite_0.geometry} material={nodes.pSphere12_Setelite_0.material} />
              </group>
              <group position={[3.04, -3.55, 3.47]}>
                <mesh geometry={nodes.pSphere13_Setelite_0.geometry} material={nodes.pSphere13_Setelite_0.material} />
              </group>
              <group position={[2.61, -3.1, 5.78]}>
                <mesh geometry={nodes.pSphere14_Setelite_0.geometry} material={nodes.pSphere14_Setelite_0.material} />
              </group>
              <mesh geometry={nodes.pSphere10_Setelite_0.geometry} material={nodes.pSphere10_Setelite_0.material} />
            </group>
          </group>
          <group name="group2" position={[-7.53, 8.2, 0.76]}>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube15_PowerGRID_0.geometry} material={nodes.pCube15_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube16_PowerGRID_0.geometry} material={nodes.pCube16_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube17_PowerGRID_0.geometry} material={nodes.pCube17_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube18_PowerGRID_0.geometry} material={nodes.pCube18_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube19_PowerGRID_0.geometry} material={nodes.pCube19_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube20_PowerGRID_0.geometry} material={nodes.pCube20_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube21_PowerGRID_0.geometry} material={nodes.pCube21_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube22_PowerGRID_0.geometry} material={nodes.pCube22_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube23_PowerGRID_0.geometry} material={nodes.pCube23_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube24_PowerGRID_0.geometry} material={nodes.pCube24_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube25_PowerGRID_0.geometry} material={nodes.pCube25_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube26_PowerGRID_0.geometry} material={nodes.pCube26_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube27_PowerGRID_0.geometry} material={nodes.pCube27_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube28_PowerGRID_0.geometry} material={nodes.pCube28_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube29_PowerGRID_0.geometry} material={nodes.pCube29_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube30_PowerGRID_0.geometry} material={nodes.pCube30_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube31_PowerGRID_0.geometry} material={nodes.pCube31_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube32_PowerGRID_0.geometry} material={nodes.pCube32_PowerGRID_0.material} />
            </group>
            <group position={[-0.02, 0, 0.01]}>
              <mesh geometry={nodes.pCube33_PowerGRID_0.geometry} material={nodes.pCube33_PowerGRID_0.material} />
            </group>
          </group>
          <group position={[-5.46, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube10_TheBOX_0.geometry} material={nodes.pCube10_TheBOX_0.material} />
          </group>
          <group position={[-4.19, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube11_TheBOX_0.geometry} material={nodes.pCube11_TheBOX_0.material} />
          </group>
          <group position={[-2.93, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube12_TheBOX_0.geometry} material={nodes.pCube12_TheBOX_0.material} />
          </group>
          <group position={[-1.66, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube13_TheBOX_0.geometry} material={nodes.pCube13_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, 1.33]}>
            <mesh geometry={nodes.pCube2_TheBOX_0.geometry} material={nodes.pCube2_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, 0.03]}>
            <mesh geometry={nodes.pCube3_TheBOX_0.geometry} material={nodes.pCube3_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, -1.27]}>
            <mesh geometry={nodes.pCube4_TheBOX_0.geometry} material={nodes.pCube4_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, -2.57]}>
            <mesh geometry={nodes.pCube5_TheBOX_0.geometry} material={nodes.pCube5_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, -3.86]}>
            <mesh geometry={nodes.pCube6_TheBOX_0.geometry} material={nodes.pCube6_TheBOX_0.material} />
          </group>
          <group position={[3.43, 7.96, -5.16]}>
            <mesh geometry={nodes.pCube7_TheBOX_0.geometry} material={nodes.pCube7_TheBOX_0.material} />
          </group>
          <group position={[-7.99, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube8_TheBOX_0.geometry} material={nodes.pCube8_TheBOX_0.material} />
          </group>
          <group position={[-6.72, 7.96, 6.34]}>
            <mesh geometry={nodes.pCube9_TheBOX_0.geometry} material={nodes.pCube9_TheBOX_0.material} />
          </group>
          <group position={[-6.45, 31.96, -4.11]}>
            <mesh geometry={nodes.pSphere11_Setelite_0.geometry} material={nodes.pSphere11_Setelite_0.material} />
          </group>
          <group position={[-6.42, 30.79, 2.49]}>
            <mesh geometry={nodes.pSphere15_Setelite_0.geometry} material={nodes.pSphere15_Setelite_0.material} />
          </group>
          <group position={[-4.16, 37.02, -6.19]}>
            <mesh geometry={nodes.pSphere16_Setelite_0.geometry} material={nodes.pSphere16_Setelite_0.material} />
          </group>
          <group position={[-0.69, 30.43, -5.2]}>
            <mesh geometry={nodes.pSphere17_Setelite_0.geometry} material={nodes.pSphere17_Setelite_0.material} />
          </group>
          <group position={[-10.24, 44.48, -2.51]}>
            <mesh geometry={nodes.pSphere18_Setelite_0.geometry} material={nodes.pSphere18_Setelite_0.material} />
          </group>
          <group position={[-11.85, 36.74, -4]}>
            <mesh geometry={nodes.pSphere19_Setelite_0.geometry} material={nodes.pSphere19_Setelite_0.material} />
          </group>
          <group position={[-6.27, 29.11, -2.98]}>
            <mesh geometry={nodes.pSphere20_Setelite_0.geometry} material={nodes.pSphere20_Setelite_0.material} />
          </group>
          <group position={[-3.38, 8.05, -0.58]}>
            <mesh geometry={nodes.polySurface6_TheBOX_0.geometry} material={nodes.polySurface6_TheBOX_0.material} />
            <mesh geometry={nodes.polySurface7_Consol_0.geometry} material={nodes.polySurface7_Consol_0.material} />
            <group position={[0, 0.2, 0]}>
              <mesh
                geometry={nodes.polySurface103_TheBOX_0.geometry}
                material={nodes.polySurface103_TheBOX_0.material}
              />
              <mesh
                geometry={nodes.polySurface104_TheBOX_0.geometry}
                material={nodes.polySurface104_TheBOX_0.material}
              />
            </group>
          </group>
          <mesh geometry={nodes.pCube100_Consol_0.geometry} material={nodes.pCube100_Consol_0.material} />
          <mesh geometry={nodes.pCube101_Consol_0.geometry} material={nodes.pCube101_Consol_0.material} />
          <mesh geometry={nodes.pCube102_Consol_0.geometry} material={nodes.pCube102_Consol_0.material} />
          <mesh geometry={nodes.pCube103_Consol_0.geometry} material={nodes.pCube103_Consol_0.material} />
          <mesh geometry={nodes.pCube104_Consol_0.geometry} material={nodes.pCube104_Consol_0.material} />
          <mesh geometry={nodes.pCube105_Consol_0.geometry} material={nodes.pCube105_Consol_0.material} />
          <mesh geometry={nodes.pCube106_Consol_0.geometry} material={nodes.pCube106_Consol_0.material} />
          <group position={[-9.8, 0, -49.75]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh
              geometry={nodes.polySurface14_Generator_0.geometry}
              material={nodes.polySurface14_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface15_Generator_0.geometry}
              material={nodes.polySurface15_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface16_Generator_0.geometry}
              material={nodes.polySurface16_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface17_Generator_0.geometry}
              material={nodes.polySurface17_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface18_Generator_0.geometry}
              material={nodes.polySurface18_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface19_Generator_0.geometry}
              material={nodes.polySurface19_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface20_Generator_0.geometry}
              material={nodes.polySurface20_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface21_Generator_0.geometry}
              material={nodes.polySurface21_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface22_Generator_0.geometry}
              material={nodes.polySurface22_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface23_Generator_0.geometry}
              material={nodes.polySurface23_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface24_Generator_0.geometry}
              material={nodes.polySurface24_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface25_Generator_0.geometry}
              material={nodes.polySurface25_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface26_Generator_0.geometry}
              material={nodes.polySurface26_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface27_Generator_0.geometry}
              material={nodes.polySurface27_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface28_Generator_0.geometry}
              material={nodes.polySurface28_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface29_Generator_0.geometry}
              material={nodes.polySurface29_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface30_Generator_0.geometry}
              material={nodes.polySurface30_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface31_Generator_0.geometry}
              material={nodes.polySurface31_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface32_Generator_0.geometry}
              material={nodes.polySurface32_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface33_Generator_0.geometry}
              material={nodes.polySurface33_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface34_Generator_0.geometry}
              material={nodes.polySurface34_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface35_Generator_0.geometry}
              material={nodes.polySurface35_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface36_Generator_0.geometry}
              material={nodes.polySurface36_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface37_Generator_0.geometry}
              material={nodes.polySurface37_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface38_Generator_0.geometry}
              material={nodes.polySurface38_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface39_Generator_0.geometry}
              material={nodes.polySurface39_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface40_Generator_0.geometry}
              material={nodes.polySurface40_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface41_Generator_0.geometry}
              material={nodes.polySurface41_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface42_Generator_0.geometry}
              material={nodes.polySurface42_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface43_Generator_0.geometry}
              material={nodes.polySurface43_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface44_Generator_0.geometry}
              material={nodes.polySurface44_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface45_Generator_0.geometry}
              material={nodes.polySurface45_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface46_Generator_0.geometry}
              material={nodes.polySurface46_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface47_Generator_0.geometry}
              material={nodes.polySurface47_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface48_Generator_0.geometry}
              material={nodes.polySurface48_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface49_Generator_0.geometry}
              material={nodes.polySurface49_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface50_Generator_0.geometry}
              material={nodes.polySurface50_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface51_Generator_0.geometry}
              material={nodes.polySurface51_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface52_Generator_0.geometry}
              material={nodes.polySurface52_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface53_Generator_0.geometry}
              material={nodes.polySurface53_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface54_Generator_0.geometry}
              material={nodes.polySurface54_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface55_Generator_0.geometry}
              material={nodes.polySurface55_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface56_Generator_0.geometry}
              material={nodes.polySurface56_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface57_Generator_0.geometry}
              material={nodes.polySurface57_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface58_Generator_0.geometry}
              material={nodes.polySurface58_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface59_Generator_0.geometry}
              material={nodes.polySurface59_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface60_Generator_0.geometry}
              material={nodes.polySurface60_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface61_Generator_0.geometry}
              material={nodes.polySurface61_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface62_Generator_0.geometry}
              material={nodes.polySurface62_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface63_Generator_0.geometry}
              material={nodes.polySurface63_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface64_Generator_0.geometry}
              material={nodes.polySurface64_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface65_Generator_0.geometry}
              material={nodes.polySurface65_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface66_Generator_0.geometry}
              material={nodes.polySurface66_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface67_Generator_0.geometry}
              material={nodes.polySurface67_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface68_Generator_0.geometry}
              material={nodes.polySurface68_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface69_Generator_0.geometry}
              material={nodes.polySurface69_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface70_Generator_0.geometry}
              material={nodes.polySurface70_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface71_Generator_0.geometry}
              material={nodes.polySurface71_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface72_Generator_0.geometry}
              material={nodes.polySurface72_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface73_Generator_0.geometry}
              material={nodes.polySurface73_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface74_Generator_0.geometry}
              material={nodes.polySurface74_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface75_Generator_0.geometry}
              material={nodes.polySurface75_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface76_Generator_0.geometry}
              material={nodes.polySurface76_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface77_Generator_0.geometry}
              material={nodes.polySurface77_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface78_Generator_0.geometry}
              material={nodes.polySurface78_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface79_Generator_0.geometry}
              material={nodes.polySurface79_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface80_Generator_0.geometry}
              material={nodes.polySurface80_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface81_Generator_0.geometry}
              material={nodes.polySurface81_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface82_Generator_0.geometry}
              material={nodes.polySurface82_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface83_Generator_0.geometry}
              material={nodes.polySurface83_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface84_Generator_0.geometry}
              material={nodes.polySurface84_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface85_Generator_0.geometry}
              material={nodes.polySurface85_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface86_Generator_0.geometry}
              material={nodes.polySurface86_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface87_Generator_0.geometry}
              material={nodes.polySurface87_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface88_Generator_0.geometry}
              material={nodes.polySurface88_Generator_0.material}
            />
            <mesh
              geometry={nodes.polySurface89_Generator_0.geometry}
              material={nodes.polySurface89_Generator_0.material}
            />
          </group>
          <mesh geometry={nodes.pCube110_Generator_0.geometry} material={nodes.pCube110_Generator_0.material} />
          <mesh geometry={nodes.pCube112_Consol_0.geometry} material={nodes.pCube112_Consol_0.material} />
          <mesh geometry={nodes.pCube113_Consol_0.geometry} material={nodes.pCube113_Consol_0.material} />
          <mesh geometry={nodes.pCube114_Consol_0.geometry} material={nodes.pCube114_Consol_0.material} />
          <mesh geometry={nodes.pCube115_Consol_0.geometry} material={nodes.pCube115_Consol_0.material} />
          <mesh geometry={nodes.pCube116_Consol_0.geometry} material={nodes.pCube116_Consol_0.material} />
          <mesh geometry={nodes.pCube117_Consol_0.geometry} material={nodes.pCube117_Consol_0.material} />
          <mesh geometry={nodes.pCube118_Consol_0.geometry} material={nodes.pCube118_Consol_0.material} />
          <mesh geometry={nodes.pCube119_Consol_0.geometry} material={nodes.pCube119_Consol_0.material} />
          <mesh geometry={nodes.pCube120_Consol_0.geometry} material={nodes.pCube120_Consol_0.material} />
          <mesh geometry={nodes.pCube121_Consol_0.geometry} material={nodes.pCube121_Consol_0.material} />
          <mesh geometry={nodes.pCube122_Consol_0.geometry} material={nodes.pCube122_Consol_0.material} />
          <mesh geometry={nodes.pCube123_Consol_0.geometry} material={nodes.pCube123_Consol_0.material} />
          <mesh geometry={nodes.pCube124_Generator_0.geometry} material={nodes.pCube124_Generator_0.material} />
          <mesh geometry={nodes.pCube14_TheBOX_0.geometry} material={nodes.pCube14_TheBOX_0.material} />
          <mesh geometry={nodes.pCube34_TheBOX_0.geometry} material={nodes.pCube34_TheBOX_0.material} />
          <mesh geometry={nodes.pCube35_Consol_0.geometry} material={nodes.pCube35_Consol_0.material} />
          <mesh geometry={nodes.pCube36_Consol_0.geometry} material={nodes.pCube36_Consol_0.material} />
          <mesh geometry={nodes.pCube50_Consol_0.geometry} material={nodes.pCube50_Consol_0.material} />
          <mesh geometry={nodes.pCube52_Consol_0.geometry} material={nodes.pCube52_Consol_0.material} />
          <mesh geometry={nodes.pCube54_Consol_0.geometry} material={nodes.pCube54_Consol_0.material} />
          <mesh geometry={nodes.pCube56_Consol_0.geometry} material={nodes.pCube56_Consol_0.material} />
          <mesh geometry={nodes.pCube58_Consol_0.geometry} material={nodes.pCube58_Consol_0.material} />
          <mesh geometry={nodes.pCube60_Consol_0.geometry} material={nodes.pCube60_Consol_0.material} />
          <mesh geometry={nodes.pCube62_Consol_0.geometry} material={nodes.pCube62_Consol_0.material} />
          <mesh geometry={nodes.pCube64_Consol_0.geometry} material={nodes.pCube64_Consol_0.material} />
          <mesh geometry={nodes.pCube66_Consol_0.geometry} material={nodes.pCube66_Consol_0.material} />
          <mesh geometry={nodes.pCube68_Consol_0.geometry} material={nodes.pCube68_Consol_0.material} />
          <mesh geometry={nodes.pCube70_Consol_0.geometry} material={nodes.pCube70_Consol_0.material} />
          <mesh geometry={nodes.pCube72_Consol_0.geometry} material={nodes.pCube72_Consol_0.material} />
          <mesh geometry={nodes.pCube74_Consol_0.geometry} material={nodes.pCube74_Consol_0.material} />
          <mesh geometry={nodes.pCube75_Consol_0.geometry} material={nodes.pCube75_Consol_0.material} />
          <mesh geometry={nodes.pCube76_Consol_0.geometry} material={nodes.pCube76_Consol_0.material} />
          <mesh geometry={nodes.pCube77_Consol_0.geometry} material={nodes.pCube77_Consol_0.material} />
          <mesh geometry={nodes.pCube78_Consol_0.geometry} material={nodes.pCube78_Consol_0.material} />
          <mesh geometry={nodes.pCube79_Consol_0.geometry} material={nodes.pCube79_Consol_0.material} />
          <mesh geometry={nodes.pCube80_Consol_0.geometry} material={nodes.pCube80_Consol_0.material} />
          <mesh geometry={nodes.pCube81_Consol_0.geometry} material={nodes.pCube81_Consol_0.material} />
          <mesh geometry={nodes.pCube82_Consol_0.geometry} material={nodes.pCube82_Consol_0.material} />
          <mesh geometry={nodes.pCube83_Consol_0.geometry} material={nodes.pCube83_Consol_0.material} />
          <mesh geometry={nodes.pCube84_Consol_0.geometry} material={nodes.pCube84_Consol_0.material} />
          <mesh geometry={nodes.pCube85_Consol_0.geometry} material={nodes.pCube85_Consol_0.material} />
          <mesh geometry={nodes.pCube86_Consol_0.geometry} material={nodes.pCube86_Consol_0.material} />
          <mesh geometry={nodes.pCube87_Consol_0.geometry} material={nodes.pCube87_Consol_0.material} />
          <mesh geometry={nodes.pCube88_Consol_0.geometry} material={nodes.pCube88_Consol_0.material} />
          <mesh geometry={nodes.pCube89_Consol_0.geometry} material={nodes.pCube89_Consol_0.material} />
          <mesh geometry={nodes.pCube90_Consol_0.geometry} material={nodes.pCube90_Consol_0.material} />
          <mesh geometry={nodes.pCube91_Consol_0.geometry} material={nodes.pCube91_Consol_0.material} />
          <mesh geometry={nodes.pCube92_Consol_0.geometry} material={nodes.pCube92_Consol_0.material} />
          <mesh geometry={nodes.pCube93_Consol_0.geometry} material={nodes.pCube93_Consol_0.material} />
          <mesh geometry={nodes.pCube94_Consol_0.geometry} material={nodes.pCube94_Consol_0.material} />
          <mesh geometry={nodes.pCube95_Consol_0.geometry} material={nodes.pCube95_Consol_0.material} />
          <mesh geometry={nodes.pCube96_Consol_0.geometry} material={nodes.pCube96_Consol_0.material} />
          <mesh geometry={nodes.pCube97_Consol_0.geometry} material={nodes.pCube97_Consol_0.material} />
          <mesh geometry={nodes.pCube98_Consol_0.geometry} material={nodes.pCube98_Consol_0.material} />
          <mesh geometry={nodes.pCube99_Consol_0.geometry} material={nodes.pCube99_Consol_0.material} />
          <mesh geometry={nodes.pCylinder100_TheBOX_0.geometry} material={nodes.pCylinder100_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder101_TheBOX_0.geometry} material={nodes.pCylinder101_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder102_TheBOX_0.geometry} material={nodes.pCylinder102_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder103_TheBOX_0.geometry} material={nodes.pCylinder103_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder104_TheBOX_0.geometry} material={nodes.pCylinder104_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder105_TheBOX_0.geometry} material={nodes.pCylinder105_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder106_TheBOX_0.geometry} material={nodes.pCylinder106_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder107_TheBOX_0.geometry} material={nodes.pCylinder107_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder108_TheBOX_0.geometry} material={nodes.pCylinder108_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder109_TheBOX_0.geometry} material={nodes.pCylinder109_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder110_TheBOX_0.geometry} material={nodes.pCylinder110_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder111_TheBOX_0.geometry} material={nodes.pCylinder111_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder113_Consol_0.geometry} material={nodes.pCylinder113_Consol_0.material} />
          <mesh geometry={nodes.pCylinder114_Consol_0.geometry} material={nodes.pCylinder114_Consol_0.material} />
          <mesh geometry={nodes.pCylinder115_Consol_0.geometry} material={nodes.pCylinder115_Consol_0.material} />
          <mesh geometry={nodes.pCylinder116_Consol_0.geometry} material={nodes.pCylinder116_Consol_0.material} />
          <mesh geometry={nodes.pCylinder117_Consol_0.geometry} material={nodes.pCylinder117_Consol_0.material} />
          <mesh geometry={nodes.pCylinder118_Consol_0.geometry} material={nodes.pCylinder118_Consol_0.material} />
          <mesh geometry={nodes.pCylinder119_Consol_0.geometry} material={nodes.pCylinder119_Consol_0.material} />
          <mesh geometry={nodes.pCylinder120_Consol_0.geometry} material={nodes.pCylinder120_Consol_0.material} />
          <mesh geometry={nodes.pCylinder121_Consol_0.geometry} material={nodes.pCylinder121_Consol_0.material} />
          <mesh geometry={nodes.pCylinder122_Consol_0.geometry} material={nodes.pCylinder122_Consol_0.material} />
          <mesh geometry={nodes.pCylinder123_Consol_0.geometry} material={nodes.pCylinder123_Consol_0.material} />
          <mesh geometry={nodes.pCylinder124_Consol_0.geometry} material={nodes.pCylinder124_Consol_0.material} />
          <mesh geometry={nodes.pCylinder125_Consol_0.geometry} material={nodes.pCylinder125_Consol_0.material} />
          <mesh geometry={nodes.pCylinder126_Consol_0.geometry} material={nodes.pCylinder126_Consol_0.material} />
          <mesh geometry={nodes.pCylinder127_Consol_0.geometry} material={nodes.pCylinder127_Consol_0.material} />
          <mesh geometry={nodes.pCylinder128_Consol_0.geometry} material={nodes.pCylinder128_Consol_0.material} />
          <mesh geometry={nodes.pCylinder129_Consol_0.geometry} material={nodes.pCylinder129_Consol_0.material} />
          <mesh geometry={nodes.pCylinder130_Consol_0.geometry} material={nodes.pCylinder130_Consol_0.material} />
          <mesh geometry={nodes.pCylinder131_Consol_0.geometry} material={nodes.pCylinder131_Consol_0.material} />
          <mesh geometry={nodes.pCylinder132_Consol_0.geometry} material={nodes.pCylinder132_Consol_0.material} />
          <mesh geometry={nodes.pCylinder133_Consol_0.geometry} material={nodes.pCylinder133_Consol_0.material} />
          <mesh geometry={nodes.pCylinder134_Consol_0.geometry} material={nodes.pCylinder134_Consol_0.material} />
          <mesh geometry={nodes.pCylinder135_Consol_0.geometry} material={nodes.pCylinder135_Consol_0.material} />
          <mesh geometry={nodes.pCylinder136_Consol_0.geometry} material={nodes.pCylinder136_Consol_0.material} />
          <mesh geometry={nodes.pCylinder137_Consol_0.geometry} material={nodes.pCylinder137_Consol_0.material} />
          <mesh geometry={nodes.pCylinder138_Consol_0.geometry} material={nodes.pCylinder138_Consol_0.material} />
          <mesh geometry={nodes.pCylinder139_Consol_0.geometry} material={nodes.pCylinder139_Consol_0.material} />
          <mesh geometry={nodes.pCylinder140_Consol_0.geometry} material={nodes.pCylinder140_Consol_0.material} />
          <mesh geometry={nodes.pCylinder141_Consol_0.geometry} material={nodes.pCylinder141_Consol_0.material} />
          <mesh geometry={nodes.pCylinder142_Consol_0.geometry} material={nodes.pCylinder142_Consol_0.material} />
          <mesh geometry={nodes.pCylinder143_Consol_0.geometry} material={nodes.pCylinder143_Consol_0.material} />
          <mesh geometry={nodes.pCylinder144_Consol_0.geometry} material={nodes.pCylinder144_Consol_0.material} />
          <mesh geometry={nodes.pCylinder145_Consol_0.geometry} material={nodes.pCylinder145_Consol_0.material} />
          <mesh geometry={nodes.pCylinder146_Consol_0.geometry} material={nodes.pCylinder146_Consol_0.material} />
          <mesh geometry={nodes.pCylinder147_Consol_0.geometry} material={nodes.pCylinder147_Consol_0.material} />
          <mesh geometry={nodes.pCylinder148_Consol_0.geometry} material={nodes.pCylinder148_Consol_0.material} />
          <mesh geometry={nodes.pCylinder149_Consol_0.geometry} material={nodes.pCylinder149_Consol_0.material} />
          <mesh geometry={nodes.pCylinder150_Consol_0.geometry} material={nodes.pCylinder150_Consol_0.material} />
          <mesh geometry={nodes.pCylinder151_Consol_0.geometry} material={nodes.pCylinder151_Consol_0.material} />
          <mesh geometry={nodes.pCylinder152_Generator_0.geometry} material={nodes.pCylinder152_Generator_0.material} />
          <mesh geometry={nodes.pCylinder153_Generator_0.geometry} material={nodes.pCylinder153_Generator_0.material} />
          <mesh geometry={nodes.pCylinder154_Generator_0.geometry} material={nodes.pCylinder154_Generator_0.material} />
          <mesh geometry={nodes.pCylinder155_Generator_0.geometry} material={nodes.pCylinder155_Generator_0.material} />
          <mesh geometry={nodes.pCylinder2_PowerGRID_0.geometry} material={nodes.pCylinder2_PowerGRID_0.material} />
          <mesh geometry={nodes.pCylinder42_Consol_0.geometry} material={nodes.pCylinder42_Consol_0.material} />
          <mesh geometry={nodes.pCylinder43_Consol_0.geometry} material={nodes.pCylinder43_Consol_0.material} />
          <mesh geometry={nodes.pCylinder44_Consol_0.geometry} material={nodes.pCylinder44_Consol_0.material} />
          <mesh geometry={nodes.pCylinder45_Consol_0.geometry} material={nodes.pCylinder45_Consol_0.material} />
          <mesh geometry={nodes.polySurface8_Setelite_0.geometry} material={nodes.polySurface8_Setelite_0.material} />
          <mesh geometry={nodes.pCylinder50_Setelite_0.geometry} material={nodes.pCylinder50_Setelite_0.material} />
          <mesh geometry={nodes.pCylinder52_TheBOX_0.geometry} material={nodes.pCylinder52_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder53_TheBOX_0.geometry} material={nodes.pCylinder53_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder54_TheBOX_0.geometry} material={nodes.pCylinder54_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder55_TheBOX_0.geometry} material={nodes.pCylinder55_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder65_PowerGRID_0.geometry} material={nodes.pCylinder65_PowerGRID_0.material} />
          <group position={[-5.34, 8.15, -9.14]} scale={0.17}>
            <mesh
              geometry={nodes.polySurface10_PowerGRID_0.geometry}
              material={nodes.polySurface10_PowerGRID_0.material}
            />
          </group>
          <mesh geometry={nodes.pCylinder67_PowerGRID_0.geometry} material={nodes.pCylinder67_PowerGRID_0.material} />
          <mesh geometry={nodes.pCylinder68_PowerGRID_0.geometry} material={nodes.pCylinder68_PowerGRID_0.material} />
          <mesh geometry={nodes.pCylinder71_Generator_0.geometry} material={nodes.pCylinder71_Generator_0.material} />
          <mesh geometry={nodes.pCylinder74_Generator_0.geometry} material={nodes.pCylinder74_Generator_0.material} />
          <mesh geometry={nodes.pCylinder77_PowerGRID_0.geometry} material={nodes.pCylinder77_PowerGRID_0.material} />
          <mesh
            geometry={nodes.polySurface109_Floor_other_0.geometry}
            material={nodes.polySurface109_Floor_other_0.material}
          />
          <mesh
            geometry={nodes.polySurface110_Floor_other_0.geometry}
            material={nodes.polySurface110_Floor_other_0.material}
          />
          <mesh
            geometry={nodes.pCylinder81_Floor_other_0.geometry}
            material={nodes.pCylinder81_Floor_other_0.material}
          />
          <mesh geometry={nodes.pCylinder82_Generator_0.geometry} material={nodes.pCylinder82_Generator_0.material} />
          <mesh geometry={nodes.pCylinder83_Generator_0.geometry} material={nodes.pCylinder83_Generator_0.material} />
          <mesh geometry={nodes.pCylinder84_Generator_0.geometry} material={nodes.pCylinder84_Generator_0.material} />
          <mesh geometry={nodes.pCylinder85_Generator_0.geometry} material={nodes.pCylinder85_Generator_0.material} />
          <mesh geometry={nodes.pCylinder86_Generator_0.geometry} material={nodes.pCylinder86_Generator_0.material} />
          <mesh geometry={nodes.pCylinder87_Generator_0.geometry} material={nodes.pCylinder87_Generator_0.material} />
          <mesh geometry={nodes.pCylinder88_Generator_0.geometry} material={nodes.pCylinder88_Generator_0.material} />
          <mesh geometry={nodes.pCylinder89_Generator_0.geometry} material={nodes.pCylinder89_Generator_0.material} />
          <mesh geometry={nodes.pCylinder90_TheBOX_0.geometry} material={nodes.pCylinder90_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder91_TheBOX_0.geometry} material={nodes.pCylinder91_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder92_TheBOX_0.geometry} material={nodes.pCylinder92_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder93_TheBOX_0.geometry} material={nodes.pCylinder93_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder94_TheBOX_0.geometry} material={nodes.pCylinder94_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder95_TheBOX_0.geometry} material={nodes.pCylinder95_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder96_TheBOX_0.geometry} material={nodes.pCylinder96_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder97_TheBOX_0.geometry} material={nodes.pCylinder97_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder98_TheBOX_0.geometry} material={nodes.pCylinder98_TheBOX_0.material} />
          <mesh geometry={nodes.pCylinder99_TheBOX_0.geometry} material={nodes.pCylinder99_TheBOX_0.material} />
          <mesh
            geometry={nodes.polySurface13_Generator_0.geometry}
            material={nodes.polySurface13_Generator_0.material}
          />
          <mesh geometry={nodes.polySurface3_TheBOX_0.geometry} material={nodes.polySurface3_TheBOX_0.material} />
          <group position={[3.31, 0, -6.68]}>
            <mesh
              geometry={nodes.polySurface91_Floor_other_0.geometry}
              material={nodes.polySurface91_Floor_other_0.material}
            />
            <mesh
              geometry={nodes.polySurface92_Floor_other_0.geometry}
              material={nodes.polySurface92_Floor_other_0.material}
            />
            <group position={[-7.96, 0, 22.17]} rotation={[0, -0.56, 0]}>
              <mesh
                geometry={nodes.polySurface100_Floor_other_0.geometry}
                material={nodes.polySurface100_Floor_other_0.material}
              />
              <group position={[-14.11, 4.57, -3.11]} rotation={[-0.13, -0.38, -0.11]}>
                <mesh
                  geometry={nodes.polySurface101_Floor_other_0.geometry}
                  material={nodes.polySurface101_Floor_other_0.material}
                />
                <mesh
                  geometry={nodes.polySurface102_Floor_other_0.geometry}
                  material={nodes.polySurface102_Floor_other_0.material}
                />
              </group>
              <mesh
                geometry={nodes.polySurface98_Floor_other_0.geometry}
                material={nodes.polySurface98_Floor_other_0.material}
              />
            </group>
            <mesh
              geometry={nodes.polySurface94_Floor_other_0.geometry}
              material={nodes.polySurface94_Floor_other_0.material}
            />
            <mesh
              geometry={nodes.polySurface95_Floor_other_0.geometry}
              material={nodes.polySurface95_Floor_other_0.material}
            />
            <mesh
              geometry={nodes.polySurface96_Floor_other_0.geometry}
              material={nodes.polySurface96_Floor_other_0.material}
            />
          </group>
          <mesh geometry={nodes.pPlane3_Floor_other_0.geometry} material={nodes.pPlane3_Floor_other_0.material} />
          <mesh geometry={nodes.pSphere21_Setelite_0.geometry} material={nodes.pSphere21_Setelite_0.material} />
          <mesh geometry={nodes.pSphere22_Setelite_0.geometry} material={nodes.pSphere22_Setelite_0.material} />
          <mesh geometry={nodes.pSphere23_Setelite_0.geometry} material={nodes.pSphere23_Setelite_0.material} />
          <mesh geometry={nodes.pSphere24_Setelite_0.geometry} material={nodes.pSphere24_Setelite_0.material} />
          <mesh geometry={nodes.pSphere25_Setelite_0.geometry} material={nodes.pSphere25_Setelite_0.material} />
          <mesh geometry={nodes.pSphere26_Setelite_0.geometry} material={nodes.pSphere26_Setelite_0.material} />
          <mesh geometry={nodes.pSphere27_Setelite_0.geometry} material={nodes.pSphere27_Setelite_0.material} />
          <mesh
            geometry={nodes.polySurface105_PowerGRID_0.geometry}
            material={nodes.polySurface105_PowerGRID_0.material}
          />
          <mesh
            geometry={nodes.polySurface106_PowerGRID_0.geometry}
            material={nodes.polySurface106_PowerGRID_0.material}
          />
          <mesh
            geometry={nodes.polySurface107_PowerGRID_0.geometry}
            material={nodes.polySurface107_PowerGRID_0.material}
          />
          <mesh
            geometry={nodes.polySurface108_PowerGRID_0.geometry}
            material={nodes.polySurface108_PowerGRID_0.material}
          />
          <mesh geometry={nodes.pTorus1_PowerGRID_0.geometry} material={nodes.pTorus1_PowerGRID_0.material} />
          <mesh geometry={nodes.pTorus2_PowerGRID_0.geometry} material={nodes.pTorus2_PowerGRID_0.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/MusicBox.gltf')
