/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
    const group = useRef()
    const { nodes, materials, animations } = useGLTF('/models/SteamMachine.gltf')
    const { actions } = useAnimations(animations, group);

    const [hovered, setHover] = useState(false);

    useEffect(() => {
        console.log("A: ", actions);
        actions["ArmatureAction"].play();
    });
    return (
        <group ref={group} {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group name="Armature" position={[-0.03, 0, 0]}>
                    <primitive object={nodes.Armature_rootJoint} />
                    <skinnedMesh
                        geometry={nodes.SteamEngine_0.geometry}
                        //material={materials.Metal}
                        skeleton={nodes.SteamEngine_0.skeleton}
                    >
                        {
                            true &&
                            <meshStandardMaterial
                                roughness={.4}
                                metalness={1}
                                attach="material"
                                color={"#A3A3A3"}
                                opacity={.1}
                                transparent={true}
                            />
                        }
                    </skinnedMesh>


                    <skinnedMesh
                        geometry={nodes.SteamEngine_1.geometry}
                        //material={materials.Painted}
                        skeleton={nodes.SteamEngine_1.skeleton}
                    >
                        {/* Testing material's opacity */}
                        <meshStandardMaterial roughness={0.5} attach="material" color={"#2d2d2d"} opacity={.2} transparent={true}/>
                    </skinnedMesh>
                
                    <skinnedMesh
                    geometry={nodes.SteamEngine_2.geometry}
                    //material={materials.Wood}
                    skeleton={nodes.SteamEngine_2.skeleton}
                    >
                        {
                            true &&
                            <meshStandardMaterial roughness={0.5} attach="material" color={"#069dd9"} opacity={.2} transparent={true}/>
                        }
                    </skinnedMesh>

                    <skinnedMesh
                    geometry={nodes.SteamEngine_3.geometry}
                    //material={materials.Brass}
                    skeleton={nodes.SteamEngine_3.skeleton}
                    >
                        {
                            true &&
                            <meshStandardMaterial roughness={0.5} attach="material" color={"#d60270"} opacity={.1} transparent={true}/>
                        }
                    </skinnedMesh>

                    <skinnedMesh
                    geometry={nodes.SteamEngine_4.geometry}
                    //material={materials.Copper}
                    skeleton={nodes.SteamEngine_4.skeleton}
                    >
                        {
                            true &&
                            <meshStandardMaterial roughness={0.5} attach="material" color={"#069dd9"} opacity={.2} transparent={true}/>
                        }
                    </skinnedMesh>

                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/SteamMachine.gltf')
